# Generated by Django 5.2.6 on 2025-10-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting_app.account', verbose_name='الحساب الرئيسي'),
        ),
    ]
