# Generated by Django 5.2.6 on 2025-12-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0005_accountingperiod_journalentry_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_reversed',
            field=models.BooleanField(default=False, verbose_name='تم عمل قيد عكسي؟'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_entry', to='accounting_app.journalentry', verbose_name='القيد العكسي'),
        ),
    ]
