# Generated by Django 5.2.6 on 2025-12-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0006_journalentry_is_reversed_journalentry_reversed_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='الرقم المسلسل'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('JE', 'Journal Entry'), ('SI', 'Sales Invoice'), ('PI', 'Purchase Invoice')], max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='accounting_app.accountingperiod')),
            ],
            options={
                'unique_together': {('doc_type', 'period')},
            },
        ),
    ]
