# Generated by Django 5.2.6 on 2025-12-18 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0007_journalentry_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice', to='accounting_app.journalentry', verbose_name='القيد الناتج عن الفاتورة'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice', to='accounting_app.journalentry', verbose_name='القيد الناتج عن الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AccountingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cfg_ap', to='accounting_app.account', verbose_name='حساب ذمم الموردين (AP)')),
                ('ar_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cfg_ar', to='accounting_app.account', verbose_name='حساب ذمم العملاء (AR)')),
                ('purchases_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cfg_purchases', to='accounting_app.account', verbose_name='حساب المشتريات/المخزون')),
                ('sales_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cfg_sales', to='accounting_app.account', verbose_name='حساب المبيعات')),
            ],
        ),
    ]
