# Generated by Django 5.2.6 on 2025-12-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0008_purchaseinvoice_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'أصول'), ('LIAB', 'خصوم'), ('EQ', 'حقوق ملكية'), ('REV', 'إيرادات'), ('EXP', 'مصاريف')], db_index=True, default='ASSET', max_length=10, verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(choices=[('DR', 'مدين'), ('CR', 'دائن')], default='DR', max_length=2, verbose_name='الطبيعة'),
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='accounting_app.account', verbose_name='الحساب')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='accounting_app.accountingperiod', verbose_name='الفترة')),
            ],
            options={
                'ordering': ('account__code',),
                'unique_together': {('period', 'account')},
            },
        ),
    ]
