# Generated by Django 5.2.6 on 2025-12-20 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0009_account_account_type_account_normal_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingconfig',
            name='retained_earnings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cfg_retained', to='accounting_app.account', verbose_name='حساب الأرباح المرحلة (Retained Earnings)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'أصول'), ('LIABILITY', 'خصوم'), ('EQUITY', 'حقوق ملكية'), ('REVENUE', 'إيرادات'), ('EXPENSE', 'مصاريف')], default='ASSET', max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(choices=[('DEBIT', 'مدين'), ('CREDIT', 'دائن')], default='DEBIT', max_length=10, verbose_name='الطبيعي'),
        ),
    ]
