# Generated by Django 5.2.6 on 2025-12-20 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0010_accountingconfig_retained_earnings_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingconfig',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cfg_cash', to='accounting_app.account', verbose_name='حساب الصندوق/البنك'),
        ),
        migrations.AddField(
            model_name='accountingconfig',
            name='cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cfg_cogs', to='accounting_app.account', verbose_name='حساب تكلفة البضاعة المباعة (COGS)'),
        ),
        migrations.AddField(
            model_name='accountingconfig',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cfg_inventory', to='accounting_app.account', verbose_name='حساب المخزون (Inventory)'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('DISBURSE', 'Disbursement')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting_app.customer')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_doc', to='accounting_app.journalentry', verbose_name='القيد الناتج عن السند')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting_app.supplier')),
            ],
        ),
    ]
