# Generated by Django 5.2.6 on 2025-12-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0011_accountingconfig_cash_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_cash', to='accounting_app.account', verbose_name='حساب الصندوق/البنك'),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='doc_type',
            field=models.CharField(choices=[('JE', 'Journal Entry'), ('SI', 'Sales Invoice'), ('PI', 'Purchase Invoice'), ('RC', 'Receipt Voucher'), ('PV', 'Payment Voucher')], max_length=10),
        ),
    ]
