# Generated by Django 5.2.6 on 2025-12-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0012_payment_cash_account_payment_voucher_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
