# Generated by Django 5.2.6 on 2025-10-06 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'حركة مخزون', 'verbose_name_plural': 'حركات المخزون'},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='reason',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product'),
        ),
        migrations.CreateModel(
            name='StockLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_remaining', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='الكمية المتبقية')),
                ('cost', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='تكلفة الوحدة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='inventory.product')),
            ],
            options={
                'verbose_name': 'طبقة مخزون',
                'verbose_name_plural': 'طبقات المخزون',
                'ordering': ['created_at'],
            },
        ),
    ]
